name: build-and-deploy
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - uses: DeLaGuardo/setup-clojure@master
        with:
          lein: 2.9.4
      - name: Maven cache
        uses: actions/cache@v2
        id: cache
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('project.clj') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Retrieve clojure deps
        run: lein deps
        if: steps.cache.outputs.cache-hit != 'true'
      - name: Run Clojure Tests
        run: lein midje

  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: run-tests
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - uses: DeLaGuardo/setup-clojure@master
        with:
          lein: 2.9.4
      - name: Maven cache
        uses: actions/cache@v2
        id: cache
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('project.clj') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Retrieve clojure deps
        run: lein deps
        if: steps.cache.outputs.cache-hit != 'true'
      - name: Build and deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
        run: sh ./build.sh

